# ESM-Tools pre-merge automation
# ==============================
# In a pull-request, if a comment contains #bump, the following steps are triggered:
#   1. merges `release` into the PR-branch (updates bumpversion values and makes sure whatever we tag in the next step has everything until that version number)
#   2. bumps the version according to the PR-branch name (`hotfix/`, `fix/` , `feature/` and `feat/` are understood)
#   3. merges PR-branch into `develop`

name: approve esm_tests changes

# Triggers the workflow on an issue comment
on:
  issue_comment:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "bump_and_merge2dev"
  update_esm_tests_info:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Run this workflow ONLY if the `issue_comment` is in a pull-request and the comment text contains `#approve-changes`
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '#approve-changes') }}

    # Sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it (`release` branch)
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: ollie
        uses: ./.github/workflows/esm_tests_computer_workflow.yml
        with:
          computer: ollie1
          update_esm_tests_info: true
          test_flags: -cng -s True
      - name: levante
        uses: ./.github/workflows/esm_tests_computer_workflow.yml
        with:
          computer: levante1
          update_esm_tests_info: true
          test_flags: -cng -s True
      - name: juwels
        uses: ./.github/workflows/esm_tests_computer_workflow.yml
        with:
          computer: jwlogin01.juwels
          update_esm_tests_info: true
          test_flags: -cng -s True
      - name: aleph
        uses: ./.github/workflows/esm_tests_computer_workflow.yml
        with:
          computer: elogin1
          update_esm_tests_info: true
          test_flags: -cng -s True
      - name: blogin
        uses: ./.github/workflows/esm_tests_computer_workflow.yml
        with:
          computer: blogin1
          update_esm_tests_info: true
          test_flags: -cng -s True
