# ESM-Tools pre-merge automation
# ==============================
# In a pull-request, if a comment contains #bump, the following steps are triggered:
#   1. merges `release` into the PR-branch (updates bumpversion values and makes sure whatever we tag in the next step has everything until that version number)
#   2. bumps the version according to the PR-branch name (`hotfix/`, `fix/` , `feature/` and `feat/` are understood)
#   3. merges PR-branch into `develop`

name: approve esm_tests changes

# Triggers the workflow on an issue comment
on:
  issue_comment:
    types: [created]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Sequence of tasks that will be executed as part of the job
  ollie:
        # Run this workflow ONLY if the `issue_comment` is in a pull-request and the comment text contains `#approve-changes`
        if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '#approve-changes') }}
        uses: ./.github/workflows/esm_tests_computer_workflow.yml
        with:
          computer: ollie1
          update_esm_tests_info: true
          test_flags: -cng -s True
  levante:
        # Run this workflow ONLY if the `issue_comment` is in a pull-request and the comment text contains `#approve-changes`
        if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '#approve-changes') }}
        uses: ./.github/workflows/esm_tests_computer_workflow.yml
        with:
          computer: levante1
          update_esm_tests_info: true
          test_flags: -cng -s True
  juwels:
        # Run this workflow ONLY if the `issue_comment` is in a pull-request and the comment text contains `#approve-changes`
        if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '#approve-changes') }}
        uses: ./.github/workflows/esm_tests_computer_workflow.yml
        with:
          computer: jwlogin01.juwels
          update_esm_tests_info: true
          test_flags: -cng -s True
  aleph:
        # Run this workflow ONLY if the `issue_comment` is in a pull-request and the comment text contains `#approve-changes`
        if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '#approve-changes') }}
        uses: ./.github/workflows/esm_tests_computer_workflow.yml
        with:
          computer: elogin1
          update_esm_tests_info: true
          test_flags: -cng -s True
  blogin:
        # Run this workflow ONLY if the `issue_comment` is in a pull-request and the comment text contains `#approve-changes`
        if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '#approve-changes') }}
        uses: ./.github/workflows/esm_tests_computer_workflow.yml
        with:
          computer: blogin1
          update_esm_tests_info: true
          test_flags: -cng -s True
