# ESM-Tools merge automation
# ==========================
# After a pull request is merged, the following steps are triggered:
#   1. Bumpversion on the release branch
#      - if the origin branch name contains "hotfix/" or "fix/" it does "bumpversion patch"
#      - if the origin branch name contains "feature/" or "feat/" it does "bumpversion minor"
#      - if the origin branch name contains none of the above runs "bumpversion patch" by default
#      - if "#patch", "#minor" or "#major" are included in any commit message of the PR, and none
#        of the above complies, then it uses the specified tag for the version bumping
#   2. Merges "release" into "develop".
#
# Note: the version bumping runs ONLY for pull-requests, pushes direcly on the release branch without
# pull-requests will not trigger version bumping.

name: merge automation

# Controls when the workflow will run
on:
  # Triggers the workflow on push release branch
  push:
    branches: [ release ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      #- name: setup bot user
      #  run: |
      #    git config --global user.email "esmtools.bot@gmail.com";
      #    git config --global user.name "esmtools-bot"
          
      - name: bump patch
        if: ${{ contains(github.event.head_commit.message, 'Merge pull request') && 
          contains(github.event.head_commit.message, 'fix/') &&
          !contains(github.event.head_commit.message, 'feat/') &&
          !contains(github.event.head_commit.message, 'feature/')
          }}
        uses: mandresm/github-bumpversion-action@v0.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

      - name: bump feature
        if: ${{ contains(github.event.head_commit.message, 'Merge pull request') && (
          contains(github.event.head_commit.message, 'feat/') ||
          contains(github.event.head_commit.message, 'feature/') ) &&
          !contains(github.event.head_commit.message, 'fix/')
          }}
        uses: mandresm/github-bumpversion-action@v0.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: minor
          
      - name: bump default
        if: ${{ contains(github.event.head_commit.message, 'Merge pull request') &&
          !contains(github.event.head_commit.message, 'feat/') &&
          !contains(github.event.head_commit.message, 'feature/') &&
          !contains(github.event.head_commit.message, 'fix/')
          }}
        uses: mandresm/github-bumpversion-action@v0.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

      - name: change author
        run: |
          git log; git blame
          echo $GITHUB_ACTOR
        
      - name: push changes
        run: |
          git push;
          git push --tags:
          
      - name: perform merge
        if: ${{ contains(github.event.head_commit.message, 'Merge pull request') }}
        run: |
          git status;
          git pull;
          git checkout release;
          git pull;
          git checkout develop;
          git merge origin/release;
          git push
