# ESM-Tests generalized workflow for computers
# ============================================

name: esm_tests_computer_workflow

# Called from other workflows
on:
  workflow_call:
    inputs:
      computer:
        required: true
        type: string
      update_esm_tests_info:
        type: boolean
        default: false
      test_flags:
        type: string
        default: "-cnge -s False"

jobs:
  computer:
    name: ${{ inputs.computer }}
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in

    steps:
    # NK: this changes working directory to fesom2
    
    - name: dummy action
      run: |
        mkdir output;
        date >  output/date.md;
        cat output/date.md;"
    
    - name: commit changes in submodule
      if: contains(${{ inputs.test_flags }}, "-s True")
      uses: cpina/github-action-push-to-another-repository@main
      env:
         SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
         API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
         source-directory: 'output'
         destination-github-username: 'mandresm'
         destination-repository-name: 'mandresm/merge_bumpversion_automation_submodule'
         user-email: mandresm@@users.noreply.github.com
         target-branch: main

